# {# pkglts, doc

site_name: fruitflow
# TODO
repo_url: https://gitlab.itkweb.fr/agro/doc
site_description: Architectural Model of Fruit Tree Flowering 
site_author: Benoit Pallas

copyright: INRAE, Cirad

theme: readthedocs

docs_dir: doc
site_dir: build/html

use_directory_urls: false
strict: true
# #}
